__all__ = (
    "partial",
    "jax",
    "reduce",
    "wraps",
    "T",
    "Any",
    "Callable",
    "Sequence",
    "Optional",
    "Union",
    "Array",
    "ArrayLike",
    "array",
    "asarray",
    "zeros",
    "zeros_like",
    "ones",
    "ones_like",
    "deg2rad",
    "rad2deg",
    "exp",
    "log",
    "sin",
    "arcsin",
    "cos",
    "arccos",
    "tan",
    "sqrt",
    "pi",
    "norm",
    "solve",
    "where",
    "prod",
    "minimum",
    "maximum",
    "mean",
    "meshgrid",
    "linspace",
    "cross",
    "hstack",
    "vstack",
    "stack",
    "concatenate",
    "eye",
    "diag",
    "dot",
    "matmul",
    "vdot",
    "grad",
    "value_and_grad",
    "jit",
    "jacfwd",
    "jacrev",
    "vmap",
    "random",
    "jnp",
    "lax",
    "jvp",
    "flatten_util",
    "selu",
    "elu",
    "tanh",
    "sigmoid",
    "swish",
    "tree_map",
    "tree_reduce",
    "tree_leaves",
    "flax",
    "nn",
    "optax",
    "jaxopt",
    "tree",
    "tree_add",
    "tree_sum",
    "tree_sub",
    "tree_div",
    "tree_mul",
    "tree_dot",
    "tree_vdot",
    "tree_scalar_mul",
    "tree_add_scalar_mul",
    "tree_l2_norm",
    "tree_negative",
    "tree_ones_like",
    "tree_zeros_like",
)

from functools import partial, reduce, wraps
import typing as T
from typing import Any, Callable, Sequence, Optional, Union

import jax
from jax.numpy import (
    array,
    asarray,
    zeros,
    zeros_like,
    ones,
    ones_like,
    eye,
    diag,
    deg2rad,
    rad2deg,
    exp,
    log,
    sin,
    arcsin,
    cos,
    arccos,
    tan,
    sqrt,
    pi,
    prod,
    hstack,
    vstack,
    stack,
    concatenate,
    dot,
    matmul,
    vdot,
    where,
    minimum,
    maximum,
    mean,
    meshgrid,
    linspace,
    cross,
)

from jax.numpy.linalg import norm, solve

import jax.numpy as jnp

from jax import Array, grad, jit, jacfwd, jacrev, vmap, jvp, value_and_grad, tree
from jax.typing import ArrayLike
import jax.lax as lax
import jax.random as random
import jax.flatten_util as flatten_util

from jax.nn import selu, elu, tanh, sigmoid, swish

from jax.tree_util import tree_map, tree_reduce, tree_leaves
import jaxopt
from jaxopt.tree_util import (
    tree_add,
    tree_sum,
    tree_sub,
    tree_div,
    tree_mul,
    tree_dot,
    tree_vdot,
    tree_scalar_mul,
    tree_add_scalar_mul,
    tree_l2_norm,
    tree_negative,
    tree_ones_like,
    tree_zeros_like,
)
import flax
from flax import linen as nn
import optax
